
message("Loading libraries and setting up the environment...")


library(ANCOMBC)
library(BBmisc)
library(DiagrammeR)
library(EnhancedVolcano)
library(Hmisc)
library(KEGGREST)
library(RColorBrewer)
library(VSURF)
library(afex)
library(ape)
library(apppleplots)
library(biomformat)
library(boot)
library(cluster)
library(clusterProfiler)
library(compositions)
library(cowplot)
library(dagitty)
library(datasets)
library(diagram)
library(dplyr)
library(dunn.test)
library(factoextra)
library(fgsea)
library(ggdag)
library(ggforce)
library(ggfortify)
library(ggh4x)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(glmmLasso)
library(glmnet)
library(glue)
library(grid)
library(gridExtra)
library(httr)
library(jsonlite)
library(lattice)
library(limma)
library(lme4)
library(lmerTest)
library(mediation)
library(mice)
library(microbiome)
library(microshades)
library(omixerRpm)
library(pheatmap)
library(phyloseq)
library(qiime2R)
library(randomForest)
library(readr)
library(readxl)
library(reshape2)
library(rstatix)
library(speedyseq)
library(stats)
library(stringr)
library(tableone)
library(tidybayes)
library(tidyr)
library(vegan)
library(utils)

message("Libraries Loaded complete!")


message("Functions loading")
#To access the functions directory why must direct to the parent directory

#A list of the function files is pulled
function_files <- list.files(paste0(getwd(),"/Functions"), pattern = "\\.R$", full.names = TRUE)
#Those functions are then sourced
lapply(function_files, source)

message("Functions loading Complete!")
