---
title: "Blastocystis Analysis"
author: "J. O'Connor"
date: "2025-09-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R markdown to perform all analysis comparison Blastocystsis to different markers

###Data is Loaded
```{r cars}

#All 18S objects have been stored in one location
euk_18S_objects <- readRDS("~/Zimbabwe-Cardiometabolic-Analysis/Data/R_Data/euk_18S_objects.RDS")

#18S objects
  #base: all processed metadata
  base <- euk_18S_objects$base
  #Euk_18S_mdf: 18S mdf data frmae
  Euk_18S_mdf <- euk_18S_objects$Euk_18S_mdf
  #base_with_18S: metadata with with 18S added
  base_with_18S <- euk_18S_objects$base_with_18S
  #Zim_all_sg_genera_pre: Unfiltered shotgun taxonomic data
  base_with_18S <- euk_18S_objects$base_with_18S
  #fecal.tax.plot.data: 16S phyloseq object 
  fecal.tax.plot.data <- euk_18S_objects$fecal.tax.plot.data

```

###Barplot Across Study Period

###Metabolic Marker DIfferences by Delta



